# -------------------------------
# Landing Page - agora.logosoft.com.py
# -------------------------------
server {
    listen 443 ssl;
    server_name agora.logosoft.com.py;

    ssl_certificate /etc/letsencrypt/live/logosoft.com.py/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/logosoft.com.py/privkey.pem;

    root /usr/share/nginx/landing;
    index index.html;

    # SPA React Landing
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name agora.logosoft.com.py;
    return 301 https://$host$request_uri;
}

# -------------------------------
# Demo - demo.agora.logosoft.com.py
# -------------------------------
server {
    listen 443 ssl;
    server_name demo.agora.logosoft.com.py;

    ssl_certificate /etc/letsencrypt/live/logosoft.com.py-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/logosoft.com.py-0001/privkey.pem;

    root /usr/share/nginx/demo;
    index index.html;

    # SPA React Demo
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API Django
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name demo.agora.logosoft.com.py;
    return 301 https://$host$request_uri;
}