services:
  db:
    image: postgis/postgis:15-3.4
    container_name: logos-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    container_name: logos-liquibase
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./liquibase:/liquibase/changelog
      - ./liquibase/drivers:/liquibase/classpath
    entrypoint: []  
    command: >
      --classpath=/liquibase/classpath/postgresql-42.7.8.jar
      --url=jdbc:postgresql://db:5432/${DB_NAME}
      --username=${DB_USER}
      --password=${DB_PASSWORD}
      --changeLogFile=/liquibase/changelog/generated/elecciones/master.yaml

  backend:
    build: ./backend
    env_file:
      - .env
    container_name: logos-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    expose:
      - "8000"   # solo expone a la red interna, no al host
    depends_on:
      - db
      - liquibase

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: logos-frontend
    volumes:
      - ./frontend/dist:/app/dist
    command: sh -c "npm run build"
    depends_on:
      - backend


  nginx:
    image: nginx:alpine
    container_name: logos-nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"   
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: