function New-OrcEnvFile {
    param (
        [Parameter(Mandatory)]
        $ctx
    )

    $projectModel = $ctx.ProjectModel
    $db = $projectModel.Database
    $project  = $projectModel.Project
    $envPath = Join-Path $project.BackendPath ".env"

    if (-not $projectModel.Database) {
        throw "projectModel.Database no está definido en el contexto"
    }

    Write-Host "Generando .env (DB_HOST=$($db.Host))"

    $env = @(
        "# Generated by orc - do not edit manually",
        "# Project: $($ctx.Project.Name)",
        "# Mode:    $($ctx.Project.Mode)",
        "",

        "DJANGO_SECRET_KEY=unsafe-dev-key",
        "DJANGO_DEBUG=true",
        "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1",

        "DB_ENGINE=$($db.Engine)",
        "DB_NAME=$($db.Name)",
        "DB_USER=$($db.User)",
        "DB_PASSWORD=$($db.Password)",
        "DB_HOST=$($db.Host)",
        "DB_PORT=$($db.Port)",

        "CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000",
        "CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000"
    )

    $env | Set-Content -Path $envPath -Encoding UTF8

    Write-Host ".env generado en $envPath"
}
