# Generated by Django 6.0 on 2025-12-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_apellidos_user_direccion_user_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
    ]
