# Generated by Django 5.2.7 on 2025-11-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'calle',
            },
        ),
        migrations.CreateModel(
            name='TipoCartel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_cartel',
            },
        ),
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, choices=[('D', 'DISPONIBLE'), ('O', 'OCUPADO'), ('I', 'INACTIVO')], max_length=1, null=True)),
                ('latitud', models.DecimalField(decimal_places=18, max_digits=21)),
                ('longitud', models.DecimalField(decimal_places=18, max_digits=21)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_completa', models.CharField(blank=True, max_length=255, null=True)),
                ('alto_metros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho_metros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_exhibicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('calles', models.ManyToManyField(blank=True, related_name='carteles', to='carteles.calle')),
            ],
            options={
                'db_table': 'cartel',
            },
        ),
        migrations.CreateModel(
            name='ImagenCartel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='carteles/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cartel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='carteles.cartel')),
            ],
            options={
                'db_table': 'imagen_cartel',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('U', 'USUARIO'), ('A', 'ADMINISTRADOR')], default='U', max_length=1)),
                ('nombre', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.AddField(
            model_name='cartel',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles', to='carteles.persona'),
        ),
        migrations.AddField(
            model_name='cartel',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles', to='carteles.tipocartel'),
        ),
    ]
