# Generated by Django 5.2.7 on 2025-10-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartel',
            name='calles',
            field=models.ManyToManyField(blank=True, null=True, related_name='carteles', to='carteles.calle'),
        ),
    ]
