# Generated by Django 5.2.7 on 2025-10-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0002_alter_cartel_calles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartel',
            name='calles',
            field=models.ManyToManyField(blank=True, related_name='carteles', to='carteles.calle'),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='latitud',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='longitud',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
    ]
