# Generated by Django 5.2.7 on 2025-10-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0003_alter_cartel_calles_alter_cartel_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartel',
            name='latitud',
            field=models.DecimalField(decimal_places=18, max_digits=21),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='longitud',
            field=models.DecimalField(decimal_places=18, max_digits=21),
        ),
    ]
