# Generated by Django 5.2.7 on 2025-12-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0003_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_inicio',
        ),
    ]
