# Generated by Django 5.2.7 on 2025-10-27 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0004_alter_cartel_latitud_alter_cartel_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('U', 'USUARIO'), ('A', 'ADMINISTRADOR')], max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='calle',
            table='calle',
        ),
        migrations.AlterModelTable(
            name='cartel',
            table='cartel',
        ),
        migrations.AlterModelTable(
            name='imagencartel',
            table='imagen_cartel',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.AlterModelTable(
            name='tipocartel',
            table='tipo_cartel',
        ),
    ]
