# Generated by Django 5.2.7 on 2025-10-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0005_alter_persona_tipo_alter_persona_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calle',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagencartel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocartel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
