# Generated by Django 5.2.7 on 2025-12-05 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0005_alter_turno_options_turno_fecha_turno_hora_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha_inicio']},
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('odontologo', 'fecha_inicio')},
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_inicio',
        ),
    ]
