import subprocess
from pathlib import Path
import argparse
import shutil
from typing import Union, Sequence
import os
import sys

# ==============================
# Constants
# ==============================

REPO_ROOT = Path(__file__).resolve().parents[2]

BACKEND_PROJECTS_DIR = REPO_ROOT / "backend" / "projects"
FRONTEND_PROJECTS_DIR = REPO_ROOT / "frontend" / "proyectos"
LIQUIBASE_ROOT = Path("docker") / "liquibase"
LIQUIBASE_PROJECTS_DIR = LIQUIBASE_ROOT / "changelog" / "projects"

BASE_REQUIREMENTS = REPO_ROOT / "backend" / "requirements.txt"

# ==============================
# Helpers
# ==============================

def run(cmd: Union[str, Sequence[str]], cwd=None, env=None, input_text=None, **kwargs):
    """
    Ejecuta un comando del sistema mostrando stdout/stderr.
    Falla inmediatamente si el comando devuelve error.

    - Si cmd es str → se ejecuta vía shell
    - Si cmd es lista → ejecución directa (recomendado)
    """
    print("dentro de run")
    print("→", cmd if isinstance(cmd, str) else " ".join(cmd))

    process = subprocess.Popen(
        cmd,
        cwd=cwd,
        env=env,
        shell=isinstance(cmd, str),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    stdout, stderr = process.communicate(input=input_text)

    if stdout:
        print(stdout)
    if stderr:
        print(stderr)

    if process.returncode != 0:
        raise RuntimeError(f"❌ Comando falló ({process.returncode})")

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("--project", required=True)

    parser.add_argument("--backend", action="store_true")
    parser.add_argument("--frontend", action="store_true")
   

    return parser.parse_args()



# ==============================
# Entrada de datos
# ==============================

def ask_project_name():
    """
    Solicita al usuario el nombre del proyecto.
    """
    nombre = input("👉 Nombre del proyecto: ").strip()
    if not nombre:
        raise ValueError("El nombre del proyecto no puede estar vacío")
    return nombre


# ==============================
# Proyecto y entorno
# ==============================

def create_project_directory(project_name):
    """
    Crea el directorio del proyecto dentro de backend/.
    """
    project_dir = BACKEND_PROJECTS_DIR / project_name
    project_dir.mkdir(parents=True, exist_ok=True)
    return project_dir


def create_virtualenv(project_dir: Path):
    """
    Crea el entorno virtual usando Python 3.14 explícitamente.
    Falla si Python 3.14 no está disponible.
    """
    python_exe = "py"

    run(
        [python_exe, "-3.14", "-m", "venv", ".venv"],
        cwd=project_dir,
        check=True,
    )

def copy_requirements(project_dir: Path):
    """
    Copia el requirements.txt base al proyecto.
    """
    python_exe = project_dir / ".venv" / "Scripts" / "python.exe"

    base_requirements = REPO_ROOT / "backend" / "requirements.txt"
    target_requirements = project_dir / "requirements.txt"

    if not base_requirements.exists():
        raise FileNotFoundError(
            f"No se encontró el requirements base en {base_requirements}"
        )

    # Copiar requirements.txt al proyecto (sobrescribe si existe)
    shutil.copy(base_requirements, target_requirements)

    
# ==============================
# Django
# ==============================

def create_django_project(project_name: str, project_dir: Path):
    """
    Inicializa el proyecto Django usando el Python del venv.
    """
    python_exe = sys.executable

    run(
        [
            python_exe,
            "-m",
            "django",
            "startproject",
            project_name,
            ".",
        ],
        cwd=project_dir,
        check=True,
    )


# ==============================
# Settings
# ==============================

def configure_settings(project_name, project_dir):
    """
    Writes runtime-driven Django settings with orco-managed apps.
    """

    settings_dir = project_dir / "config" / "settings"
    settings_dir.mkdir(parents=True, exist_ok=True)

    legacy_settings_path = project_dir / project_name / "settings.py"

    if legacy_settings_path.exists():
        legacy_settings_path.unlink()

    # ------------------------------------------------------------------
    # orc_apps.py
    # ------------------------------------------------------------------

    orc_apps_path = settings_dir / "orc_apps.py"

    orc_apps_content = '''"""
AUTOGENERATED BY ORCO.
Do not edit manually.
"""

ORC_APPS = [
    "apps.base",
]
'''
    orc_apps_path.write_text(orc_apps_content)

    # ------------------------------------------------------------------
    # base.py
    # ------------------------------------------------------------------

    base_settings_path = settings_dir / "base.py"

    base_settings = f'''"""
Django settings for {project_name} project.

Runtime-driven configuration.
Apps are managed by ORCO.
"""

from pathlib import Path
import os
import sys
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# -------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parents[3]

BACKEND_DIR = Path(
    os.environ.get("BACKEND_DIR", BASE_DIR)
).resolve()

APPS_DIR = BACKEND_DIR / "apps"

for p in (BACKEND_DIR, APPS_DIR):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

ENV_PATH = BASE_DIR / "{project_name}" / ".env"

if ENV_PATH.exists():
    load_dotenv(ENV_PATH)
else:
    raise ImproperlyConfigured(f".env file not found at {{ENV_PATH}}")

# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------

def env(name: str) -> str:
    value = os.getenv(name)
    if value is None:
        raise ImproperlyConfigured(f"Missing environment variable: {{name}}")
    return value

# -------------------------------------------------------------------
# Core settings
# -------------------------------------------------------------------

SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env("DJANGO_DEBUG").lower() == "true"
ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS").split(",")

# -------------------------------------------------------------------
# Application definition
# -------------------------------------------------------------------

from .orc_apps import ORC_APPS

DJANGO_BASE_APPS = [
    "corsheaders",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

INSTALLED_APPS = DJANGO_BASE_APPS + ORC_APPS

# -------------------------------------------------------------------
# Middleware
# -------------------------------------------------------------------

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "projects.{project_name}.config.urls"

TEMPLATES = [
    {{
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {{
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        }},
    }},
]

WSGI_APPLICATION = "projects.{project_name}.{project_name}.wsgi.application"

# -------------------------------------------------------------------
# Database (runtime-controlled)
# -------------------------------------------------------------------

DATABASES = {{
    "default": {{
        "ENGINE": env("DB_ENGINE"),
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }}
}}

# -------------------------------------------------------------------
# Authentication
# -------------------------------------------------------------------

AUTH_USER_MODEL = "base.User"

AUTH_PASSWORD_VALIDATORS = [
    {{"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"}},
    {{"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"}},
    {{"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"}},
    {{"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"}},
]

# -------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# Static files
# -------------------------------------------------------------------

STATIC_URL = "static/"

# -------------------------------------------------------------------
# CORS / CSRF (runtime-controlled)
# -------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS").split(",")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS").split(",")
CORS_ALLOW_CREDENTIALS = True
'''
    base_settings_path.write_text(base_settings)

    # ------------------------------------------------------------------
    # __init__.py
    # ------------------------------------------------------------------

    init_path = settings_dir / "__init__.py"
    init_path.write_text("from .base import *\n")

def configure_entrypoints(project_name, project_dir):
    """
    Rewrites Django entrypoints to use orco-managed settings.
    """

    settings_module = "config.settings.base"

    # ------------------------------------------------------------------
    # manage.py
    # ------------------------------------------------------------------

    manage_path = project_dir / "manage.py"
    manage_content = f'''#!/usr/bin/env python
import os
import sys

def main():
    os.environ.setdefault(
        "DJANGO_SETTINGS_MODULE",
        "{settings_module}"
    )
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise
    execute_from_command_line(sys.argv)

if __name__ == "__main__":
    main()
'''
    manage_path.write_text(manage_content)

    # ------------------------------------------------------------------
    # wsgi.py
    # ------------------------------------------------------------------

    wsgi_path = project_dir / project_name / "wsgi.py"
    wsgi_content = f'''import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault(
    "DJANGO_SETTINGS_MODULE",
    "{settings_module}"
)

application = get_wsgi_application()
'''
    wsgi_path.write_text(wsgi_content)

    # ------------------------------------------------------------------
    # asgi.py (optional)
    # ------------------------------------------------------------------

    asgi_path = project_dir / project_name / "asgi.py"
    if asgi_path.exists():
        asgi_content = f'''import os
from django.core.asgi import get_asgi_application

os.environ.setdefault(
    "DJANGO_SETTINGS_MODULE",
    "{settings_module}"
)

application = get_asgi_application()
'''
        asgi_path.write_text(asgi_content)


# ==============================
# VS Code
# ==============================

def configure_vscode(project_dir):
    """
    Crea la configuración recomendada para VS Code.
    """
    vscode_dir = project_dir / ".vscode"
    vscode_dir.mkdir(exist_ok=True)

    (vscode_dir / "settings.json").write_text(
        """{
  "python.defaultInterpreterPath": ".venv/Scripts/python.exe",
  "python.analysis.extraPaths": [
    "..",
    "../apps"
  ],
  "python.analysis.typeCheckingMode": "basic",
  "python.analysis.autoSearchPaths": true,
  "python.terminal.activateEnvironment": false,
  "editor.formatOnSave": true
}
""",
        encoding="utf8",
    )

    (vscode_dir / "extensions.json").write_text(
        """{
  "recommendations": [
    "ms-python.python",
    "ms-python.vscode-pylance"
  ]
}
""",
        encoding="utf8",
    )


# ==============================
# Environment & DB
# ==============================

def create_postgres_schema(args):
    """
    Crea un schema PostgreSQL si no existe.
    """
    schema_name = args.project
    try:
        import psycopg2  # type: ignore

        conn = psycopg2.connect(
            dbname="postgres",
            user=args.db_user,
            password=args.db_password,
            host=args.db_host,
            port=args.db_port,
        )
        conn.autocommit = True
        cur = conn.cursor()

        cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema_name}";')

        cur.close()
        conn.close()

        print(f"✅ Schema '{schema_name}' creado o ya existente")

    except Exception as e:
        print(f"⚠️ Error creando schema '{schema_name}': {e}")


# ==============================
# Liquibase
# ==============================

def register_project_in_liquibase(project_name: str) -> None:
    """
    Registra un nuevo proyecto en Liquibase.

    - Crea el directorio del proyecto en changelog/projects/
    - Crea un changelog inicial vacío (001-init.yaml)

    No modifica el master changelog.
    No ejecuta Liquibase.
    """
    project_dir = LIQUIBASE_PROJECTS_DIR / project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    initial_changelog = project_dir / "001-init.yaml"

    if not initial_changelog.exists():
        initial_changelog.write_text(
            f"""databaseChangeLog:
  - comment: Changelog inicial del proyecto {project_name}
""",
            encoding="utf8",
        )

        print(f"🧩 Liquibase: proyecto '{project_name}' registrado")
    else:
        print(f"ℹ️ Liquibase: proyecto '{project_name}' ya existe")

# ==============================
# Frontend
# ==============================

def create_frontend_skeleton(project_name):
    project_dir = FRONTEND_PROJECTS_DIR / project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    if any(project_dir.iterdir()):
        raise RuntimeError("El directorio frontend no está vacío")

    return project_dir


def patch_vite_config(project_dir):
    vite_config = project_dir / "vite.config.js"

    if not vite_config.exists():
        raise FileNotFoundError(
            f"No se encontró vite.config.js en {project_dir}"
        )

    content = vite_config.read_text(encoding="utf-8")

    if "server:" in content:
        # Ya fue modificado antes
        return

    patched = content.replace(
        "export default defineConfig({",
        "export default defineConfig({\n  server: {\n    port: 3000,\n  },"
    )

    vite_config.write_text(patched, encoding="utf-8")

def configure_urls(project_name, project_dir):
    """
    Writes orco-managed Django URL configuration.

    The project itself does not define routes.
    All routes are provided by installed orco apps.
    """

    # ------------------------------------------------------------------
    # config/urls/
    # ------------------------------------------------------------------

    urls_dir = project_dir / "config" / "urls"
    urls_dir.mkdir(parents=True, exist_ok=True)

    # base.py
    base_urls_path = urls_dir / "base.py"
    base_urls_content = '''"""
Base URL configuration.

Routes are provided by ORCO-managed apps.
"""

from django.urls import include, path
from config.settings.orc_apps import ORC_APPS

urlpatterns = []

for app in ORC_APPS:
    try:
        urlpatterns.append(
            path("", include(f"{app}.urls"))
        )
    except ModuleNotFoundError:
        pass
'''
    base_urls_path.write_text(base_urls_content)

    # __init__.py
    init_path = urls_dir / "__init__.py"
    init_path.write_text("from .base import urlpatterns\n")

    # ------------------------------------------------------------------
    # project urls.py (proxy)
    # ------------------------------------------------------------------

    project_urls_path = project_dir / project_name / "urls.py"
    project_urls_content = '''"""
Project URL configuration.

Delegates routing to ORCO-managed apps.
"""

from django.urls import path, include

urlpatterns = [
    path("api/", include("config.urls")),
]
'''
    project_urls_path.write_text(project_urls_content)


# ==============================
# Main
# ==============================

def main():
    args = parse_args()

    if args.project:
        project_name = args.project
    else:
        project_name = ask_project_name()
    if not args.backend and not args.frontend:
        args.backend = True
        args.frontend = True

    project_dir = create_project_directory(project_name)

    print(f"\n🚀 Creando proyecto '{project_name}'\n")

    if args.backend:
        # create_virtualenv(project_dir)
        copy_requirements(project_dir)
        create_django_project(args.project, project_dir)
        configure_settings(args.project, project_dir)
        configure_entrypoints(project_name, project_dir)
        configure_urls(project_name, project_dir)
        configure_vscode(project_dir)
        # create_postgres_schema(args)
        # register_project_in_liquibase(args.project)

    if args.frontend:
        create_frontend_skeleton(args.project)

    print("\n🎉 Proyecto creado correctamente")
    print("📌 El schema será gestionado por Liquibase")
    print(f"cd backend/{project_name}")
    print("python manage.py runserver")


if __name__ == "__main__":
    main()
